version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
      - dependency-name: io.sundr:sundr-maven-plugin
        versions:
          - ">= 0.2"
      - dependency-name: com.diffplug.spotless:spotless-maven-plugin
        versions:
          - ">= 2.3"
