# Java files
java:
  - '**/*.java'

# XML files
xml:
  - '**/*.xml'
  - '**/*.xsd'
  - '**/*.wsdl'

# Documentation
documentation:
  - '**/*.md'
  - '**/*.adoc'
  - '**/*.txt'
  - 'docs/**/*'

# Configuration files
config:
  - '.github/**/*'
  - '.editorconfig'
  - '.gitattributes'
  - '.gitignore'
  - 'pom.xml'
  - '**/*.properties'
  - '**/*.yml'
  - '**/*.yaml'

# Test files
test:
  - '**/test/**/*'
  - '**/tests/**/*'
  - '**/*Test.java'
  - '**/*Tests.java'
  - '**/*IT.java'

# Build files
build:
  - '**/target/**/*'
  - '**/build/**/*'
  - '**/out/**/*'
  - '**/bin/**/*'

# Dependencies
dependencies:
  - 'pom.xml'

# Security
security:
  - '**/security/**/*'
  - '**/auth/**/*'
  - '**/crypto/**/*' 