version: '3'

vars:
  GOOS: "{{default OS .GOOS}}"
  MVNW: '{{if eq .GOOS "windows"}}mvnw.cmd -B -ntp{{else}}./mvnw -B -ntp{{end}}'
  SLEEP: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
  default:
    cmds:
      - task: test

  test:
    deps: [ format ]
    cmds:
      - "{{.MVNW}} clean verify"

  format:
    cmds:
      - "{{.MVNW}} spotless:apply"

  release-perform:
    cmds:
      - "{{.MVNW}} release:clean release:prepare"
      - "{{.MVNW}} release:perform"

  deploy-local:
    deps: [ test ]
    cmds:
      - "{{.MVNW}} deploy"

  deploy-central:
    deps: [ test ]
    cmds:
      - "{{.MVNW}} deploy -Prelease"

  sonar:
    cmds:
      - "{{.MVNW}} sonar:sonar -Dsonar.token=$SONAR_TOKEN" # read from shell env
