# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Maven Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

env:
  MAVEN_ARGS: -B -ntp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Detect Maven Wrapper
        run: |
          if [ -f mvnw ]; then
            echo "MAVEN_EXEC=./mvnw" >> $GITHUB_ENV
          else
            echo "MAVEN_EXEC=mvn" >> $GITHUB_ENV
          fi

      - name: Build with Maven
        run: ${MAVEN_EXEC} verify

      - uses: actions/checkout@v4
        name: Checkout rose-microservice
        with:
          repository: rose-group/rose-microservice
          path: rose-microservice

      - name: Test rose-microservice
        run: |
          cd rose-microservice
          mvn versions:update-parent -DallowSnapshots=true -N
          git diff pom.xml
          mvn install

  quality:
    needs: [ build ]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: quality
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with docs and coverage
        run: mvn verify -Pcoverage javadoc:javadoc

      - name: build with sonar
        run: mvn sonar:sonar -Psonar -Dsonar.token=${{secrets.SONAR_TOKEN}}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}