name: Maven Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'
  schedule:
    - cron: '55 5 * * 5'

jobs:
  build:
    name: build
    uses: rosestack/.github/.github/workflows/maven-build.yml@main
    secrets: inherit
