name: Maven Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'README*'

jobs:
  build:
    name: build
    uses: rosestack/.github/.github/workflows/build.yml@main
    secrets: inherit
