name: PR Automation
on:
  pull_request_target:
    types:
      - closed

jobs:
  pr-automation:
    name: PR Automation
    # https://github.com/apache/maven-gh-actions-shared/blob/v4/.github/workflows/pr-automation.yml
    uses: apache/maven-gh-actions-shared/.github/workflows/pr-automation.yml@v4
