name: Release
run-name: Release ${{github.event.inputs.tag}}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to release."
        required: true
        default: "main"
      version:
        description: "Release version"
        required: true
        default: "0.0.1"
      nextVersion:
        description: "Next version"
        required: true
        default: "0.0.2-SNAPSHOT"

permissions:
  attestations: write
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Perform Release
    uses: rose-group/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      branch: ${{github.event.inputs.branch}}
      version: ${{github.event.inputs.version}}
      nextVersion: ${{github.event.inputs.nextVersion}}