name: Maven Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to release."
        required: true
        type: string
        default: "main"
      version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      nextVersion:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"

permissions:
  contents: write

jobs:
  release:
    name: Release
    uses: rose-group/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      branch: ${{github.event.inputs.branch}}
      version: ${{github.event.inputs.version}}
      nextVersion: ${{github.event.inputs.nextVersion}}