name: Maven Release
run-name: Perform ${{github.event.inputs.tag || github.ref_name}} Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to release."
        required: true
        type: string
        default: "main"
      version:
        description: "Release version"
        required: true
        type: string
        default: "0.0.1"
      nextVersion:
        description: "Next version"
        required: true
        type: string
        default: "0.0.2-SNAPSHOT"

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perform-release:
    name: Perform Release
    uses: rose-group/.github/.github/workflows/release.yml@main
    secrets: inherit
    with:
      branch: ${{steps.metadata.outputs.branch}}
      version: ${{steps.metadata.outputs.version}}
      nextVersion: ${{steps.metadata.outputs.next-version}}