name: Maven Release by Manual

on:
  workflow_dispatch:
    inputs:
      current-version:
        description: "Release version"
        required: true
        default: "0.0.1"
      next-version:
        description: "Next version"
        required: true
        default: "0.0.2-SNAPSHOT"

jobs:
  release:
    name: Release
    uses: rosestack/.github/.github/workflows/release-by-manual.yml@main
    secrets: inherit
    with:
      current-version: ${{github.event.inputs.current-version}}
      next-version: ${{github.event.inputs.next-version}}
