name: Release by project

on:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    if: ${{ github.event.pull_request.merged == true}}
    uses: rose-group/.github/.github/workflows/release-by-project.yml@main
    secrets: inherit