name: Maven Release by File

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

jobs:
  release:
    name: Release
    if: ${{ github.event.pull_request.merged == true}}
    uses: rosestack/.github/.github/workflows/release-by-file.yml@main
    secrets: inherit
