name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_release_draft:
    name: Update Release Draft
    uses: rosestack/.github/.github/workflows/release-drafter.yml@main
